development:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") %>
  # Используем PostgreSQL для работы между контейнерами
  
test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") %>
  # Используем PostgreSQL для ActionCable в production
